In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(r"C:\Users\wwwil\Downloads\insurance.csv")

In [9]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [12]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_count}")

Number of duplicate rows found: 0

In [13]:
df = df.drop_duplicates().reset_index(drop=True)
print(f"Dataset shape after dropping duplicates: {df.shape}")

Dataset shape after dropping duplicates: (1337, 7)

In [22]:
BMI_as_bins = [0, 24.99, 29.99, float('inf')]
BMI_labels = ['Normal', 'Overweight', 'Obese']

In [23]:
df['bmi_category'] = pd.cut(df['bmi'], bins=BMI_as_bins, labels=BMI_labels)

In [24]:
df

,age,sex,bmi,children,smoker,region,charges,bmi_category
0,19,female,27.900,0,yes,southwest,16884.92400,Overweight
1,18,male,33.770,1,no,southeast,1725.55230,Obese
2,28,male,33.000,3,no,southeast,4449.46200,Obese
3,33,male,22.705,0,no,northwest,21984.47061,Normal
4,32,male,28.880,0,no,northwest,3866.85520,Overweight
...,...,...,...,...,...,...,...,...
1332,50,male,30.970,3,no,northwest,10600.54830,Obese
1333,18,female,31.920,0,no,northeast,2205.98080,Obese
1334,18,female,36.850,0,no,southeast,1629.83350,Obese
1335,21,female,25.800,0,no,southwest,2007.94500,Overweight
1336,61,female,29.070,0,yes,northwest,29141.36030,Overweight

In [26]:
df.to_csv(r'C:\Users\wwwil\Downloads\Cleaned_insurance_data.csv', index=False)
print("\nSuccess!")

Success!